DROP TABLE IF EXISTS TEST;
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE TEST(
	TESTINT INTEGER
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE MEMBER(
	NO INTEGER AUTO_INCREMENT PRIMARY KEY COMMENT '사번',
	ID VARCHAR(50) NOT NULL UNIQUE COMMENT '아이디',
	PWD VARCHAR(255) NOT NULL COMMENT '비밀번호',
	ENROLLDATE DATETime DEFAULT CURRENT_TIMESTAMP COMMENT '가입일' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO test
(
  TESTINT
)
VALUES
(
  20
);

CREATE TABLE ROLE(
	ROLE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	ROLE VARCHAR(255) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO ROLE
(
  ROLE
)
VALUES
(
  'ADMIN'
);

INSERT INTO ROLE
(
  ROLE
)
VALUES
(
  'MEMBER'
);

CREATE TABLE USER_ROLE(
	USER_ID INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
