DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
	NO INTEGER AUTO_INCREMENT PRIMARY KEY COMMENT '사번',
	ID VARCHAR(50) NOT NULL UNIQUE COMMENT '아이디',
	PWD VARCHAR(255) NOT NULL COMMENT '비밀번호',
	ENROLLDATE DATETime DEFAULT CURRENT_TIMESTAMP COMMENT '가입일' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE AUTHORITY(
	ID VARCHAR(50) REFERENCES MEMBER(ID),
	ROLE VARCHAR(100) CHECK IN ('ROLE_MEMBER', 'ROLE_ADMIN')
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
